<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/about</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/contact</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/arts</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/vids</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/category/articles</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/category/videos</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/tags/articles</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/tags/videos</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/videos/author</loc>
    </sitemap>
    <sitemap>
        <loc>http://santonamedia.com/sitemap.xml/articles/author</loc>
    </sitemap>
</sitemapindex>
