<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/home</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/about</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/contact</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/articles</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/videos</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/category/articles</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/category/videos</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/tags/articles</loc>
    </sitemap>
    <sitemap>
        <loc>https://santonamedia.com/sitemap.xml/tags/videos</loc>
    </sitemap>
</sitemapindex>
